# fly.toml file generated for joelhooks-redis-cache on 2021-11-30T15:20:26-08:00

app = "joelhooks-redis-cache"


[env]
  PRIMARY_REGION = "sea"

[experimental]
  auto_rollback = false

[mount]
  destination = "/data"
  source = "redis_server"

[[services]]
  internal_port = 6379
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = []
    port = "10000"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
