app = "kcd-redis"

[experimental]
auto_rollback = false

[env]
  PRIMARY_REGION = "dfw"

[mount]
  destination = "/data"
  source = "redis_server"

[[services]]
internal_port = 6379
protocol      = "tcp"

  [services.concurrency]
  hard_limit = 25
  soft_limit = 20

  [[services.ports]]
  handlers = []
  port     = "10000"

  [[services.tcp_checks]]
  interval = 10000
  timeout  = 2000